endpointUrl: http://localhost:8080
method: POST
curlExecutable: curl
connectTimeoutSeconds: 3
requestTimeoutSeconds: 3
outputDirectory: results
payloadTypes:
  - contentType: json,xml,form,multipart
    transferEncoding: NA,GZ,CSB
    payloadSize: 20K,1M
