---
endpointUrl: "http://localhost:8080"
method: "POST"
curlExecutable: "curl"
connectTimeoutSeconds: 3
requestTimeoutSeconds: 3
outputDirectory: "results"
curlArguments: []
payloadTypes:
- contentType: "json"
  transferEncoding: "NA"
  payloadSize: "SM"
- contentType: "json"
  transferEncoding: "NA"
  payloadSize: "CM"
- contentType: "json"
  transferEncoding: "NA"
  payloadSize: "LG"
- contentType: "json"
  transferEncoding: "GZ"
  payloadSize: "SM"
- contentType: "json"
  transferEncoding: "GZ"
  payloadSize: "CM"
- contentType: "json"
  transferEncoding: "GZ"
  payloadSize: "LG"
- contentType: "json"
  transferEncoding: "CSB"
  payloadSize: "SM"
- contentType: "json"
  transferEncoding: "CSB"
  payloadSize: "CM"
- contentType: "json"
  transferEncoding: "CSB"
  payloadSize: "LG"
- contentType: "json"
  transferEncoding: "CCB"
  payloadSize: "SM"
- contentType: "json"
  transferEncoding: "CCB"
  payloadSize: "CM"
- contentType: "json"
  transferEncoding: "CCB"
  payloadSize: "LG"
- contentType: "json"
  transferEncoding: "CLB"
  payloadSize: "SM"
- contentType: "json"
  transferEncoding: "CLB"
  payloadSize: "CM"
- contentType: "json"
  transferEncoding: "CLB"
  payloadSize: "LG"
- contentType: "xml"
  transferEncoding: "NA"
  payloadSize: "SM"
- contentType: "xml"
  transferEncoding: "NA"
  payloadSize: "CM"
- contentType: "xml"
  transferEncoding: "NA"
  payloadSize: "LG"
- contentType: "xml"
  transferEncoding: "GZ"
  payloadSize: "SM"
- contentType: "xml"
  transferEncoding: "GZ"
  payloadSize: "CM"
- contentType: "xml"
  transferEncoding: "GZ"
  payloadSize: "LG"
- contentType: "xml"
  transferEncoding: "CSB"
  payloadSize: "SM"
- contentType: "xml"
  transferEncoding: "CSB"
  payloadSize: "CM"
- contentType: "xml"
  transferEncoding: "CSB"
  payloadSize: "LG"
- contentType: "xml"
  transferEncoding: "CCB"
  payloadSize: "SM"
- contentType: "xml"
  transferEncoding: "CCB"
  payloadSize: "CM"
- contentType: "xml"
  transferEncoding: "CCB"
  payloadSize: "LG"
- contentType: "xml"
  transferEncoding: "CLB"
  payloadSize: "SM"
- contentType: "xml"
  transferEncoding: "CLB"
  payloadSize: "CM"
- contentType: "xml"
  transferEncoding: "CLB"
  payloadSize: "LG"
- contentType: "form"
  transferEncoding: "NA"
  payloadSize: "SM"
- contentType: "form"
  transferEncoding: "NA"
  payloadSize: "CM"
- contentType: "form"
  transferEncoding: "NA"
  payloadSize: "LG"
- contentType: "form"
  transferEncoding: "GZ"
  payloadSize: "SM"
- contentType: "form"
  transferEncoding: "GZ"
  payloadSize: "CM"
- contentType: "form"
  transferEncoding: "GZ"
  payloadSize: "LG"
- contentType: "form"
  transferEncoding: "CSB"
  payloadSize: "SM"
- contentType: "form"
  transferEncoding: "CSB"
  payloadSize: "CM"
- contentType: "form"
  transferEncoding: "CSB"
  payloadSize: "LG"
- contentType: "form"
  transferEncoding: "CCB"
  payloadSize: "SM"
- contentType: "form"
  transferEncoding: "CCB"
  payloadSize: "CM"
- contentType: "form"
  transferEncoding: "CCB"
  payloadSize: "LG"
- contentType: "form"
  transferEncoding: "CLB"
  payloadSize: "SM"
- contentType: "form"
  transferEncoding: "CLB"
  payloadSize: "CM"
- contentType: "form"
  transferEncoding: "CLB"
  payloadSize: "LG"
- contentType: "multipart"
  transferEncoding: "NA"
  payloadSize: "SM"
- contentType: "multipart"
  transferEncoding: "NA"
  payloadSize: "CM"
- contentType: "multipart"
  transferEncoding: "NA"
  payloadSize: "LG"
- contentType: "multipart"
  transferEncoding: "GZ"
  payloadSize: "SM"
- contentType: "multipart"
  transferEncoding: "GZ"
  payloadSize: "CM"
- contentType: "multipart"
  transferEncoding: "GZ"
  payloadSize: "LG"
- contentType: "multipart"
  transferEncoding: "CSB"
  payloadSize: "SM"
- contentType: "multipart"
  transferEncoding: "CSB"
  payloadSize: "CM"
- contentType: "multipart"
  transferEncoding: "CSB"
  payloadSize: "LG"
- contentType: "multipart"
  transferEncoding: "CCB"
  payloadSize: "SM"
- contentType: "multipart"
  transferEncoding: "CCB"
  payloadSize: "CM"
- contentType: "multipart"
  transferEncoding: "CCB"
  payloadSize: "LG"
- contentType: "multipart"
  transferEncoding: "CLB"
  payloadSize: "SM"
- contentType: "multipart"
  transferEncoding: "CLB"
  payloadSize: "CM"
- contentType: "multipart"
  transferEncoding: "CLB"
  payloadSize: "LG"
